server:
  port: 8080
spring:
  application:
    name: "DemoReintentos"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3000
          max-attempts: 3
          multiplier: 2.0
          max-interval: 3000

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

#spring.rabbitmq.host: localhost
#spring.rabbitmq.port: 5729
#spring.rabbitmq.username: guest
#spring.rabbitmq.password: guest


app:
  async:
    with-d-l-q-retry: true
    max-retries: 3
    retry-delay: 3000